CREATE TABLE todo (
	id INT NOT NULL AUTO_INCREMENT,
	description VARCHAR(140) NULL,
	done BOOLEAN NOT NULL,
	id_user INT NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT FOREIGN KEY (id_user) REFERENCES user(id)
)